### ISSUE TITLE
Time machine label bug

### ISSUE THREAD

**Issue by timsofteng** [emmanueltouzery/agitator.nvim#10]
Steps to reproduce:
1. Open time machine on some file.
2. Quit from time machine's buffer with `:q`. 

Time machine label with info will not disappear. 
With `q` it works correctly.

**Comment by emmanueltouzery** [comment]
correct, I noticed that recently, or maybe the more "generic" case if you display another buffer in that window, without even closing the time-machine buffer. I'll do something about this yes.

**Comment by emmanueltouzery** [comment]
should be fixed now!
