### ISSUE TITLE
Git find file opens empty file with telescope new vertical buffer

### ISSUE THREAD

**Issue by timsofteng** [emmanueltouzery/agitator.nvim#11]
Steps to reproduce:
1. open_file_git_branch()
2. Pick branch.
3. `Go to file selection as a vsplit` for the file (C-v default in telescope).

It works with opening in current buffer.

**Comment by timsofteng** [comment]
@emmanueltouzery may you take a look at this issue please?

**Comment by emmanueltouzery** [comment]
i'll get to it but it's low priority for me i have plenty of other things that would bring me personally more value in the short term.

**Comment by emmanueltouzery** [comment]
finally got to that one :)

**Comment by timsofteng** [comment]
@emmanueltouzery 
Thanks!
Just a little issue. Open empty buffer just with nvim without any arguments and than try to follow steps. File will be opened in the new window but with additional empty window. 3 windows but user expects 2.

**Comment by emmanueltouzery** [comment]
I only get two windows with these steps. First i have only the empty buffer (or to be more precise i'm using a startup plugin, alpha.nvim). then i pick a branch and a file, press C-v, I now have two buffers, the one with the file on the left, the startup alpha.nvim on the right?
