### ISSUE TITLE
How to remap for time_machine

### ISSUE THREAD

**Issue by habanerotostitos** [emmanueltouzery/agitator.nvim#12]
hi I really like the time machine feature of your plugin

I'm trying to change time machines previous/next keymapping since my terminal keymap overrides it

do you have any recommendations on how to keymap? I want to just remap from \<c-p\> and \<c-n\> to left and right when I'm in the time machine window

i tried this function from looking in your code which works, but it remaps globally instead of only when I'm inside the time machine window 

sorry for the newbie question

```
vim.keymap.set("n", "<left>", function()
    require("agitator").git_time_machine_previous()
end)
```

**Comment by emmanueltouzery** [comment]
this wasn't really supported until now. check the latest readme changes on the time_machine function, specifically the new options.

**Comment by habanerotostitos** [comment]
awesome 

thank you

heres what I ended up with if it helps anyone else searching this. it creates a vertical split and uses that. I had to use `=` rather than `:` as mentioned in README to assign the configuration values, but I might be doing it an unintended way.

```
vim.keymap.set("n", "<leader>g", function()
	vim.cmd("vsplit")
	require("agitator").git_time_machine({
		use_current_win = true,
		set_custom_shortcuts = function(code_bufnr)
			vim.keymap.set("n", "<left>", function()
				require("agitator").git_time_machine_previous()
			end, { buffer = code_bufnr })
			vim.keymap.set("n", "<right>", function()
				require("agitator").git_time_machine_next()
			end, { buffer = code_bufnr })
			vim.keymap.set("n", "<c-h>", function()
				require("agitator").git_time_machine_copy_sha()
			end, { buffer = code_bufnr })
			vim.keymap.set("n", "q", function()
				require("agitator").git_time_machine_quit()
			end, { buffer = code_bufnr })
		end,
		popup_last_line = "<left> Previous | <right> Next | <c-h> Copy SHA | [q]uit",
	})
end)
```

**Comment by emmanueltouzery** [comment]
oops, the `:` for popup_last_line was wrong in the readme, fixed now :+1:
