### ISSUE TITLE
Not working for custom formats

### ISSUE THREAD

**Issue by franroa** [emmanueltouzery/agitator.nvim#13]
Hi, nice plugin!

I have tried to install it and realized that it only worked with the default git log command. I use a formatted one, which is not understood by the plugin.

Are there any plans to support customization?

Thanks!

**Comment by emmanueltouzery** [comment]
can you give the relevant section of your config file, so i can reproduce?

there is a whole concept of porcelain vs plumbing commands in git. and i could pass in --pretty to git log to work around that.

so it seems fixable.

**Comment by franroa** [comment]
Hi, indeed this is a problem with pretty and format. Not really a git guru, though and cannot solve it:

```
[pretty]
  dateline = format:*%C(yellow)%h%Creset%x09%Cred%<(13)%an%Creset%x09%Cblue%ad%Creset%x09%s

[format] ; TODO: make this work when agitator plugin can understand it
  pretty = dateline

```

**Comment by emmanueltouzery** [comment]
sorry, just so that i won't waste time, where do you put these settings?

**Comment by franroa** [comment]
No problem,

I put the file under the file: **~/.config/git/config**

**Comment by emmanueltouzery** [comment]
try again, i think it should be ok now!
