### ISSUE TITLE
Added options

### ISSUE THREAD

**Issue by timsofteng** [emmanueltouzery/agitator.nvim#2]
Hello. Is it possible to add option to move focus to blame window when it opens?
And add some hotkey like `gq` in fugitive to close it.

**Comment by emmanueltouzery** [comment]
sorry, I missed that bug. but why would you want that? what are you going to do in the blame window? maybe copy some rows from there?

**Comment by emmanueltouzery** [comment]
to close it you can use `git_blame_close()`, so you can map a shortcut to that function call. agitator won't do that for you, because it's expected that everyone may want different shortcuts.

**Comment by emmanueltouzery** [comment]
closing due to lack of information, feel free to reopen with extra info!
